name: app_atelie

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  vector_math: ^2.1.4
  characters: ^1.3.0
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
